<a href="https://colab.research.google.com/github/MaitreePimple/Data-Science/blob/main/numpy_part_4_(random_operations_%2C_String_Operation_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.random.random(1) #random an array is genrated the number in () indictaes how many array you want genrated

array([0.43252186])

In [6]:
np.random.random(10)

array([0.43131336, 0.94390599, 0.67161609, 0.96967375, 0.26539169,
       0.54878807, 0.66348275, 0.62105547, 0.50563092, 0.59397635])

In [8]:
np.random.random((2,2))

array([[0.60461061, 0.6065357 ],
       [0.60719274, 0.75580725]])

In [9]:
np.random.randint(1,10) #randint is used to randomly genrate the integare from the given range

8

In [11]:
np.random.randint(1,20,(2,2)) #by using this you can randomly genrate 2 array by random digit from given range

array([[18,  4],
       [ 9, 14]])

In [13]:
np.random.randint(1,100,(3,4,5))

array([[[73, 57, 77, 89, 80],
        [53, 70, 61, 32, 83],
        [78,  7, 61, 99, 73],
        [11, 63, 58, 56, 50]],

       [[51, 26, 38, 57, 46],
        [10, 17, 17, 76, 63],
        [14, 31, 25, 71, 80],
        [40, 72,  3, 67, 99]],

       [[10, 95, 45, 85, 67],
        [77, 73, 50, 28, 94],
        [13, 60, 14, 45, 16],
        [53,  4, 57, 17, 59]]])

In [14]:
np.random.randn(2,2) #by using randn negative numbers are printed

array([[-1.88720162,  1.97000712],
       [ 0.45750362,  0.27104192]])

In [15]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.random.shuffle(a)
a

array([2, 7, 1, 6, 5, 9, 8, 3, 4])

In [20]:
np.random.choice(a)


3

In [28]:
s1='Maitree is my name'
s2='Indian'

In [22]:
np.char.add(s1,s2) #concadetion

array('MaitreeIndian', dtype='<U13')

In [25]:
np.char.upper(s1) #Makes all the characters in upper case of the given string

array('MAITREE', dtype='<U7')

In [26]:
np.char.lower(s2) #Make all the char of str in lowercase

array('indian', dtype='<U6')

In [29]:
np.char.split(s1) #splits the array where space is given

array(list(['Maitree', 'is', 'my', 'name']), dtype=object)

In [30]:
s3 = 'Maitree is my \nname'
np.char.splitlines(s3) #splits the str were it find \n command

array(list(['Maitree is my ', 'name']), dtype=object)

In [32]:
np.char.replace(s1,'name','Friend')

array('Maitree is my Friend', dtype='<U20')

In [35]:
print('******************Maitree*************')

******************Maitree*************


In [34]:
print(np.char.center('Maitree',40,fillchar='*'))

****************Maitree*****************
