<a href="https://colab.research.google.com/github/MaitreePimple/Data-Science/blob/main/NumpyPart1(basic_operations_%2C_slicing_operation_and_arange_%2Crehsape%2Cravel%2Cflatten).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst = [1,2,3,4,5] #in python list it can store only one deminision array in it of any type but by using numpy we can store multiple deminision array
print(lst)

[1, 2, 3, 4, 5]


In [ ]:
print ('1D ARRAY')
a = np.array([1,2,3,4,50])
print(a)

#-------------------------------------

print('2D ARRAY')
b = np.array([[1,2],[6,7]])
print(b)

#----------------------------------------

print('3D ARRAY')
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

#-------------------------------------------

print('4D ARRAY')
d = np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]])
print(d)

1D ARRAY
[ 1  2  3  4 50]
2D ARRAY
[[1 2]
 [6 7]]
3D ARRAY
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4D ARRAY
[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [ ]:
type(a) #type of data

numpy.ndarray

In [ ]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)
#SIZE GIVE NUMBER OF ELEMNETS PRESENT IN ARRAY

5
4
9
16


In [ ]:
#shape = (rows,columns)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(5,)
(2, 2)
(3, 3)
(4, 4)


In [ ]:
#dtype = TYPE OF DATA PRSENT IN THE ARRAY

print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
int64
int64
int64


In [ ]:
e = np.array([[1,2,3,4.2,5],[6,7,8.9,9,10],[11,12,13,14,15]])
print(e.dtype)

float64


In [ ]:
#arr.transpose() IT REPLACE ROWS INTO COLUMNS AND COLUMNS INTO ROWS
#a.transpose() //array([ 1,  2,  3,  4, 50])
#b.transpose()  //array([[1, 6],[2, 7]])
#c.transpose() //array([[1, 4, 7],[2, 5, 8],[3, 6, 9]])
#d.transpose()  //array([[ 1,  3,  5,  7],[ 2,  4,  6,  8],[ 3,  5,  7,  9], [ 4,  6,  8, 10]])
#e.transpose() //array([[ 1. ,  6. , 11. ],[ 2. ,  7. , 12. ],[ 3. ,  8.9, 13. ],[ 4.2,  9. , 14. ],[ 5. , 10. , 15. ]])





array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

In [ ]:
#np.empty((rows,cols),dtype) // (rows,cols) is called as tuple  (in these we get empty array with random numbers)

#np.empty((2,3),dtype=int)
np.empty((4,4),dtype=float)

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323, 4.9e-323]])

In [ ]:
#np.ones((rows,cols),dtype)

#np.ones((2,3),dtype=int)
#x = np.ones((3,4),dtype=float)
#z
#y = np.ones(6)
#y
#z = np.ones((2,3),dtype=int)
#z

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#np.zeros((rows,columns),dtype)

#x = np.zeros(4)
#x
#y = np.zeros((4,8), dtype = int)
#y
#z = np.ones((4,8),dtype=str)
#z

#z = np.ones((4,8),dtype = bool)
#z

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [1]:
#np.arange (start,end,step) ITS LIKE A LOOP WHICH PRINTS THE VALUE VALUE GIVEN IN PATICULAR RANGE

import numpy as np
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [2]:
a = np.arange(1,20,2) #odd series
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [8]:
a = np.arange(2,20,2) #Even series
print(a)

[ 2  4  6  8 10 12 14 16 18]


arr.reshape((rows,cols)) : It helps in reshaping the array

In [9]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
b = np.arange(1,100,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [15]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

flatten : 1. reverse the effect of reshape. 2. returns only copy of the original array . 3. slower then ravel and 4 Flatten is a method of an ndarray object

In [16]:
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

a.ravel : 1 return only reference / view of original array . 2 If you modify the array youwould notice that the value of original array also changes . 3 Ravel is faster that flatten() as it does not occupy any memory .4 Ravel is a library - Level Function .

In [17]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

ARRAY SLICING OPERATION

In [18]:
a = np.arange(1,51)
a = a.reshape(10,5)
print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [19]:
a[0]

array([1, 2, 3, 4, 5])

In [20]:
a[1,2]

8

In [21]:
a[2,4]

15

In [23]:
a[2]

array([11, 12, 13, 14, 15])

In [24]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [28]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [30]:
a[:,3]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [33]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [36]:
a[:,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [37]:
a[2:5,2:5].dtype

dtype('int64')