<a href="https://colab.research.google.com/github/MaitreePimple/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5] #in python list it can store only one deminision array in it of any type but by using numpy we can store multiple deminision array
print(lst)

[1, 2, 3, 4, 5]


In [12]:
print ('1D ARRAY')
a = np.array([1,2,3,4,50])
print(a)

#-------------------------------------

print('2D ARRAY')
b = np.array([[1,2],[6,7]])
print(b)

#----------------------------------------

print('3D ARRAY')
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

#-------------------------------------------

print('4D ARRAY')
d = np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]])
print(d)

1D ARRAY
[ 1  2  3  4 50]
2D ARRAY
[[1 2]
 [6 7]]
3D ARRAY
[[1 2 3]
 [4 5 6]
 [7 8 9]]
4D ARRAY
[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [10]:
type(a) #type of data

numpy.ndarray

In [13]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)
#SIZE GIVE NUMBER OF ELEMNETS PRESENT IN ARRAY

5
4
9
16


In [14]:
#shape = (rows,columns)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(5,)
(2, 2)
(3, 3)
(4, 4)


In [15]:
#dtype = TYPE OF DATA PRSENT IN THE ARRAY

print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
int64
int64
int64


In [19]:
import numpy as np
e = np.array ([[1,2,3,4.5,4.6],
             [2.3,4,5,6],
             [6.0,7,8,9]])
print(e.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [21]:
e = np.array([[1,2,3,4.2,5],[6,7,8.9,9,10],[11,12,13,14,15]])
print(e.dtype)

float64


In [27]:
#arr.transpose() IT REPLACE ROWS INTO COLUMNS AND COLUMNS INTO ROWS
#a.transpose() //array([ 1,  2,  3,  4, 50])
#b.transpose()  //array([[1, 6],[2, 7]])
#c.transpose() //array([[1, 4, 7],[2, 5, 8],[3, 6, 9]])
#d.transpose()  //array([[ 1,  3,  5,  7],[ 2,  4,  6,  8],[ 3,  5,  7,  9], [ 4,  6,  8, 10]])
#e.transpose() //array([[ 1. ,  6. , 11. ],[ 2. ,  7. , 12. ],[ 3. ,  8.9, 13. ],[ 4.2,  9. , 14. ],[ 5. , 10. , 15. ]])





array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

In [30]:
#np.empty((rows,cols),dtype) // (rows,cols) is called as tuple  (in these we get empty array with random numbers)

#np.empty((2,3),dtype=int)
np.empty((4,4),dtype=float)

array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [1.5e-323, 2.0e-323, 2.5e-323, 3.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323, 4.9e-323]])

In [38]:
#np.ones((rows,cols),dtype)

#np.ones((2,3),dtype=int)
#x = np.ones((3,4),dtype=float)
#z
#y = np.ones(6)
#y
#z = np.ones((2,3),dtype=int)
#z

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
#np.zeros((rows,columns),dtype)

#x = np.zeros(4)
#x
#y = np.zeros((4,8), dtype = int)
#y
#z = np.ones((4,8),dtype=str)
#z

#z = np.ones((4,8),dtype = bool)
#z

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])